import Foundation

// Import the generated UniFFI C header
#if canImport(agent_coreFFI)
import agent_coreFFI
#endif

// Include the generated Swift bindings
// This file is generated by UniFFI and contains all the FFI code
#if SKIP_UNIFFI_IMPORT
// For testing without the Rust library
#else
// The actual implementation comes from agent_core.swift in vendor/uniffi-swift
// which gets included via the bridging header
#endif
